build fix: added missing declaration of mhl_dir_plus_file (reported by andrew_b)
    ./configure --enable-samba && make
../vfs/libvfs-mc.a(smbfs.o): In function `smbfs_get_path':
/home/andrew/work.c/mc/mc.master/vfs/smbfs.c:1214: undefined reference to `mhl_str_dir_plus_file'
collect2: ld returned 1 exit status

Signed-off-by: Sergei Trofimovich <slyfox@inbox.ru>