build fix: added missing declaration of mhl_dir_plus_file
./configure --enable-charset && make
    charsets.c: In function 'load_codepages_list':
    charsets.c:51: warning: implicit declaration of function 'mhl_str_dir_plus_file'
    charsets.c:51: warning: assignment makes pointer from integer without a cast

Signed-off-by: Sergei Trofimovich <slyfox@inbox.ru>